version: '3'
services:
 web:
   image: php:5.6-apache
   ports:
    - "8092:80"
   volumes:
    - ./www/:/var/www/html/

  web:
   image: php:5.6-apache
   ports:
    - "8082:80"
   volumes:
    - ./www/:/var/www/html/