version: '3'
services:
 web:
   build: .
   ports:
    - "8090:80"
   volumes:
    - ./sandbox.ini:/usr/local/etc/php/conf.d/sandbox.ini
    - ./flag_h0w2execute_arb1trary_c0de:/var/www/flag_h0w2execute_arb1trary_c0de
    - ./www/:/var/www/html/